### ISSUE TITLE
Truncated PNG being generated

### ISSUE THREAD

**Issue by robertmain** [hacksalot/HackMyResume#100]
HMR is generating PNGs that are cut off. For example:
![out](https://cloud.githubusercontent.com/assets/537684/12208367/4ef34136-b644-11e5-819c-012beb33d5b4.png)

**Comment by hacksalot** [comment]
Thanks @robertmain -- this should be resolved when we move PNGs to CLI-based generation through Phantom, the way PDFs work now.

**Comment by hacksalot** [comment]
There have been some recent changes to how PNGs are generated:

1. Removed [**webshot**](https://github.com/brenden/node-webshot) since it mandates a PhantomJS install and we're trying not to impose that, or any other specific engine, on the user.

2. Use Phantom's CLI (instead of API) to generate PNGs. This follows the same method we're using for PDF generation.

PNGs now show the full resume, albeit with some sizing issues that need to be resolved.

**Comment by hacksalot** [comment]
Closing this as the truncation has been resolved in recent versions. There are some visual glitches with PNG generation in certain cases (not related to truncation) that would need a separate issue.
