### ISSUE TITLE
Speaking section not rendered

### ISSUE THREAD

**Issue by umpirsky** [hacksalot/HackMyResume#101]
Not sure if it is HackMyResume issue or themes issue, but with both modern and jsonresume-theme-slick themes "speaking" section is not rendered at all.

I noticed that this section is supported only by FRESH format.

**Comment by StevenBlack** [comment]
It's the theme.  have a [look here](https://github.com/dfmcphee/jsonresume-theme-slick/blob/master/resume.template).

**Comment by umpirsky** [comment]
@StevenBlack Yes, I saw, but with default theme (modern) it is also not there.

**Comment by StevenBlack** [comment]
Looks like [Speaking was added Dec 8 2015](https://github.com/fluentdesk/FRESCA/commit/e23d8d656839022a1ab5e9fe4529dfeb8818d427).

So the default themes lag by considerable time.  Modern is [here](https://github.com/jsonresume/jsonresume-theme-modern).

**Comment by hacksalot** [comment]
@StevenBlack Yes, for sure. We had a pretty big initial lag because at the time there wasn't tool support for theme inheritance, partials, or a cross-engine helper apparatus. Theme updates should flow more quickly now, and getting full coverage of the model in all FRESH themes is one of the major two requirements for moving fresh-themes out of beta. (The other being NPM/Bower/etc packaging.)

**Comment by umpirsky** [comment]
Thanks folks.

But it will never be supported in `jsonresume-theme-modern`, right? Since it is FRESH specific.

**Comment by hacksalot** [comment]
That question is probably best put to the JSON Resume folks -- when JSON Resume 1.0.0 is released presumably the themes will be updated too, but that would be up to the individual authors. In the meantime, it would be pretty easy to extend the theme to include this -- eg, take a fork & make the changes, or submit an issue here for a comparable FRESH version.

There's also support brewing for random injection of content into the resume HTML after generation has run, which would allow you to a) generate the resume and then b) inject additional sections using jQuery-style selectors.

**Comment by umpirsky** [comment]
In deed, thanks @hacksalot.

**Comment by umpirsky** [comment]
I just tried forked https://github.com/umpirsky/jsonresume-theme-slick and added:

```
{{#if resume.speaking.length}}
	<h1>Test</h1>
{{/if}}
```

When I checkout it in separate folder I get:

```
$ node_modules/.bin/hackmyresume BUILD  -d resume.json TO resume.html -t jsonresume-theme-slick 

*** HackMyResume v1.5.2 ***
Reading resume: resume.json
Applying JSONRESUME-THEME-SLICK theme (2 formats)
Generating HTML resume: resume.html
ERROR: HACKMYSTATUS is not defined
ReferenceError: HACKMYSTATUS is not defined
    at JRSTheme.open (node_modules/hackmyresume/src/core/jrs-theme.js:76:28)
    at Class.themeFromMoniker (node_modules/hackmyresume/src/generators/template-generator.js:249:26)
    at Class.module.exports.BaseGenerator.extend.invoke (node_modules/hackmyresume/src/generators/template-generator.js:96:40)
    at Class.module.exports.BaseGenerator.extend.generate (node_modules/hackmyresume/src/generators/template-generator.js:129:26)
    at single (node_modules/hackmyresume/src/verbs/build.js:193:32)
    at node_modules/hackmyresume/src/verbs/build.js:85:17
    at Array.forEach (native)
    at build (node_modules/hackmyresume/src/verbs/build.js:84:13)
    at Command.execVerb (node_modules/hackmyresume/src/index.js:177:28)
    at Command.<anonymous> (node_modules/hackmyresume/src/index.js:110:16)
```

Why this happens?

Then I tried to edit `node_modules/jsonresume-theme-slick/resume.template` directly.

But it is not rendered. My resume.json does contain `speaking` section.
Any idea how I can debug it?

Thanks.

**Comment by hacksalot** [comment]
Should be fixed shortly -- looks like the `speaking` section isn't being carried over to the JRS format prior to invoking the theme. This is an HMR bug, not a JSON Resume one. I'll update here in a half hour or so and you should be able to pick up from dev or grab the official 1.6.0 this afternoon.

**Comment by umpirsky** [comment]
@hacksalot Thanks a lot, that was blazing fast! :+1: 

What about `ReferenceError: HACKMYSTATUS is not defined`? Any idea why this happens when I use custom theme location checkouted from my github repo?

**Comment by hacksalot** [comment]
There are a couple bugs here, good catch. HACKMYSTATUS is used in that spot without ever being `require()ed` so that's why the `ReferenceError`. It happens to be on a rarely-executed code path, which is why our (current) tests didn't catch it. The error being thrown in that specific spot relates to not finding the `package.json` for the JSON Resume theme. Lastly, we're currently not pushing all unknown/extra fields during conversion between resume formats : )

**Comment by umpirsky** [comment]
@hacksalot Understood. Thanks for detailed explanation! :+1:

**Comment by hacksalot** [comment]
Should be fixed in 1.6.0. If not, leave a comment here or open a new issue. Thanks~

**Comment by robertmain** [comment]
It doesn't seem to be working for me but that's partly because I don't know what format the speaking section should take and partly because apart from man pages I can't find any mention of it in the code (and trust me, i've grep'd my little head off :smile: )

The newly generated resumes dont include it
	{
		"basics": {
			"name": "Robert Main",
			"label": "Software Developer",
			"email": "someone@domain.com",
			"summary": "Experienced web developer specializing in great web applications with a strong slant toward modern web technologies and frameworks such as Angular and Node.JS",
			"location": {
				"address": "",
				"city": "",
				"region": "",
				"postalCode": "",
				"countryCode": ""
			},
			"profiles": [
				{
					"network": "GitHub",
					"username": "robertmain",
					"url": "http://github.com/robertmain"
				}, 
				{
					"network": "Bitbucket",
					"username": "robertmain",
					"url": "http://bitbucket.com/robertmain"
				}
			]
		},
		"work": [
			{
				"company": "University of Aberdeen",
				"position": "Junior Software Developer",
				"website": "http://abdn.ac.uk",
				"startDate": "2014-08-01",
				"summary": "Project team member working on new online learning environment for medical students as well as general day-to-day support tasks.",
				"highlights": []
			},
			{
				"company": "Farmison and Co.",
				"position": "Junior Web Developer",
				"website": "http://farmison.com",
				"startDate": "2013-11-01",
				"endDate": "2014-01-01",
				"summary": "Responsible for custom database reports as well as front and back end development.",
				"highlights": []
			}
		],
		"volunteer": [
			{
				"organization": "Highland Innovation Event",
				"position": "Web developer",
				"startDate": "2012-04-03",
				"endDate": "2012-04-03",
				"summary": "Member of the tecnical team representing Inverness College, produced a treasure scavenger hunt using QR codes for the event",
				"highlights": []
			},
			{
				"organization": "Inverness Monster Science Festival",
				"position": "Technical Crew",
				"startDate": "2011-03-05",
				"endDate": "2011-03-05",
				"summary": "Technical team member responsible for representing the computing department of Inverness College at the Inverness Monster Science Festival",
				"highlights": []
			},
			{
				"organization": "Highland Web Group",
				"position": "Guest Speaker",
				"website": "http://www.meetup.com/Highland-Web-Group/",
				"startDate": "2014-03-12",
				"endDate": "2014-03-12",
				"summary": "Delivered a talk on Node.JS",
				"highlights": []
			}
		],
		"education": [
			{
				"institution": "Napier University",
				"area": "Computing",
				"studyType": "Bachelor",
				"startDate": "2012-09-01",
				"endDate": "2013-05-01",
				"gpa": "",
				"courses": []
			},
			{
				"institution": "The University of The Highland and Islands",
				"area": "Computing",
				"studyType": "Bachelor",
				"startDate": "2009-09-01",
				"endDate": "2012-05-01",
				"gpa": "",
				"courses": []
			}
		],	
		"events": [{
			"conference": "JSConf EU 2013",
			"date": "2013-xx-xx",
			"title": "Stop Breaking the Web",
			"link": "https://www.youtube.com/watch?v=OSEXpsVcTxI"
		}],
		"skills": [
			{
				"name": "Backend",
				"level": "master",
				"keywords": [
					"php",
					"CodeIgniter",
					"Zend Framework",
					"Node.JS",
					"Sails.JS",
					"Real Time Applications"
				]
			},
			{
				"name": "Frontend",
				"level": "master",
				"keywords": [
					"JavaScript",
					"AngularJS",
					"Data Binding",
					"HTML",
					"HTML5",
					"CSS3"
				]
			},
			{
				"name": "Version Control",
				"level": "master",
				"keywords": [
					"Git",
					"Mercurial",
					"SVN"
				]
			},
			{
				"name": "Devops",
				"level": "intermediate",
				"keywords": [
					"Continuous delpoyment",
					"Continuous integration",
					"Jenkins",
					"PHPDoc",
					"Doc Generation",
					"Unit testing",
					"Gulp.js"
				]
			},
			{
				"name": "Mobile Development",
				"level": "beginner",
				"keywords": [
					"Android",
					"Firefox OS"
				]
			},
			{
				"name": "Linux Server Administration",
				"level": "intermediate",
				"keywords": [
					"Debian",
					"CentOS",
					"Ubuntu",
					"RHEL"
				]
			},
			{
				"name": "Native Programming Languages",
				"level": "beginner",
				"keywords": [
					"Java"
				]
			}
		],
		"languages": [
			{
				"language": "English",
				"fluency": "Native speaker"
			}
		],
		"interests": [
			{
				"name": "Photography",
				"keywords": []
			}
		]
	}

and it seems not to be in the examples under `/test` unless I've missed it somehow...

**Comment by hacksalot** [comment]
@robertmain Only FRESH/FRESCA resumes currently support `speaking`. JSON Resume will support something similar in the future, but it's not in the 0.0.0. We could support it for JRS in the interim, but not as a root-level property, at least, not without violating the schema. :-/

**Comment by robertmain** [comment]
Hmm...maybe I should convert to FRESH/FRESCA then. I believe HMR can do this conversion - yes?

**Comment by hacksalot** [comment]
It can with `hackmyresume convert` but there are good reasons to keep both formats. I use FRESH as the "single source of truth", but maintain a synced JRS copy side by side with it. Note that any translation glitch from FRESH to JRS is a HackMyResume bug: the conversion has to be 100% solid. Right now it's maybe ~95% solid.

**Comment by robertmain** [comment]
So what should I do? Convert to FRESH but keep the JRS around? What are the reasons for keeping both around?

**Comment by hacksalot** [comment]
The official recommendation from the FRESH workflow is that it really doesn't matter, provided the source format you're using supports straightforward translation to FRESH or another user-first format (FRESH is currently the only truly *user-first* format that I know of). Since you can convert JRS to FRESH through HackMyResume and FluentCV -- or any tool that can map JSON to slightly different JSON -- that condition is fulfilled. If JRS doesn't have the sections you like, use FRESH -- but check back when JRS 1.0.0 drops. Or vice versa. Conversion between these should feel trivial, and if it's not, then the tool isn't doing its job.

Think of it like this. From the FRESH perspective, *all* of these formats are output/destination formats. You are the (only) source of truth. JSON Resume is a container into which you pour that source of truth when you want to use something JRS related, like a theme or tool. FRESH is a container that helps you store that truth, analyze, and pour it into other containers including JRS.

**Comment by umpirsky** [comment]
@hacksalot I tried with HackMyResume v1.7.4 and FRESH format, in my theme `resume.speaking.length` is still false.

**Comment by hacksalot** [comment]
Speaking should show up -- if you try with [Jane's resume](https://github.com/fresh-standard/fresh-resume-exemplar/blob/master/resume/jane-resume.json) (you can `npm install fresh-resume-exemplar`) do you see the Speaking section?

**Comment by umpirsky** [comment]
@hacksalot Yes, working with default theme, must be on my side then. Thanks.

**Comment by hacksalot** [comment]
Cool, let me know.
