### ISSUE TITLE
line breaks cause errors but can't tell which line

### ISSUE THREAD

**Issue by mtantawy** [hacksalot/HackMyResume#137]
Accidental line breaks within strings/values cause errors when trying to validate, analyze, or build which is expected.

The problem is the error fails to indicate the line responsible and instead shows ???

I was able to point the issue by checking the JSON on http://jsonlint.com/

**Comment by hacksalot** [comment]
Thanks for the report @mtantawy. As we are using the same library that jsonlint uses, we should be reporting identical line and column info. Will address for next release.

**Comment by hacksalot** [comment]
Incidentally, this is a bit more involved than just catching an exception and reporting the line and column number. `JSON.parse` doesn't return that information consistently, neither do most other parsers. What HMR actually does is:

1. Parse.
2. Catch the exception.
3. Re-parse with a syntax-error aware library.
4. Since no single library currently catches *all* possibly syntax errors, re-parse with a second syntax-error-aware library if the first re-parse didn't pick up the line/column info.

Even then, there are edge cases -- yours is one of them -- where the column number won't be returned (and also isn't returned by, say, JSONLint.com). So for now it will be line + column for most syntax errors, but line-only for the embedded line break error specifically.

**Comment by mtantawy** [comment]
Yeah at least showing the line number is better than nothing.
Appreciated the effort!
