### ISSUE TITLE
projects section is not generated when converting FRESH to JRS

### ISSUE THREAD

**Issue by serginator** [hacksalot/HackMyResume#195]
Given a correct resume.json in FRESH format, if you run `hackmyresume CONVERT resume.json resume-jrs.json` the JRS one will not have `projects` section.

**Comment by hacksalot** [comment]
Thanks! Fixed in v1,9.0 (fluentdesk/fresh-jrs-converter/pull/4)

**Comment by hacksalot** [comment]
We'll have to tweak this behavior since `projects` causes JRS resumes not to validate, because the schema declares that additional root-level properties are illegal. When it comes to properties that exist in the FRESH schema but don't exist in the JSON Resume schema, there are a few options:

- omit any non-validating fields that don't have an obvious JRS corollary (current behavior)
- include all fields and be OK with invalidating the resume; let the user sort it out (your PR)
- include said fields in a non-root level node in the JRS resume; allows resume to validate
- wait until the next JRS schema version & toolset

**Comment by hacksalot** [comment]
Fixed in 1.9.0-beta
