### ISSUE TITLE
New JSON resume has meta with format "FRESH@0.1.0"

### ISSUE THREAD

**Issue by mikeycgto** [hacksalot/HackMyResume#63]
I am unsure if this is correct for the JSON format.

```json
"meta": {
  "format": "FRESH@0.1.0",
  "version": "0.1.0"
}
```

**Comment by pmbenjamin** [comment]
Same here. Was this addressed somewhere else?

**Comment by hacksalot** [comment]
Hi, thanks for the report. Can you verify your command syntax? It should be:

`hackmyresume new myresume.json -f jrs`

The `-f` parameter switches the format to JRS.

**Comment by pmbenjamin** [comment]
I see. I assumed the default would be in JSON format.
Just out of curiosity, what is the difference between JSON and FRESH formats?
I've googled "fresh vs json", but got no relevant results.

**Comment by hacksalot** [comment]
This will be documented more clearly in v1.3.x, but the basic difference between the *formats* is:

- JSON Resume is a nascent standard (v0.0.0, with v1.0.0 in development), with the goal of establishing an open resume format.

- FRESH is a standards-friendly format, also JSON, with the goal of enabling lossless conversions between other source formats (including JSON Resume), providing implicit Markdown support across multiple output formats, and establishing a durable source of truth for resume and career data. It's designed as a superset, and is free to include stuff that other standards might exclude because of genericity or suitability requirements.

The bigger difference is between the themes:

- FRESH themes have a multiformat requirement: not just HTML but MS Word, PDF, and (soon) LaTeX. And they guarantee the flowing of Markdown to those formats.

- JSON Resume themes are more numerous and provide a wider choice of designs, but they're typically HTML-oriented (although PDF, text, and other conversions are available). HMR also does its best (in v1.3, shortly) to flow Markdown to these formats, but under JSON Resume much of that is left to the theme.

In HMR v1.3 you'll be able generate any theme (FRESH or JRS) from either format (FRESH or JRS), because of the convertability. HMR v1.2 already does this to a degree.

**Comment by pmbenjamin** [comment]
@hacksalot , thank you for the information. You've been very helpful.
