### ISSUE TITLE
generate pdf and png

### ISSUE THREAD

**Issue by zhuangya** [hacksalot/HackMyResume#86]
@hacksalot as we discussed before in separate places, i think the pdf and png generator should work like this:

- if therer is LaTeX on the user's computer, generate pdf and png by LaTeX for better quality, easier workflow etc.
- if there is no LaTeX, user phantomjs instead.

do i understand this right? 

and other questions:

- looks like we have to install phantomjs, maybe ditch pdf/png, or create another tool(plugin) for this two format?
- do we still need `wkhtmltopdf`? if so, where it stands?

**Comment by hacksalot** [comment]
Sounds good. Some thoughts:

- Let the user choose the PDF engine! A typical PDF integration is 100 lines or less. For "point and click" PDF generators like Phantom or wkhtmltopdf, it's almost more work for the user to install the subsystem than it is to write the generator. That's not to say we have to support every PDF engine, but that we should support a decent selection and put this decision in the hands of users who care, with an acceptable default for users who don't.

- Don't require users to install PDF engines they don't want, or to install *any* PDF engine (or even think about PDFs) if they're not actively interested in the PDF format. We should take this as far as exposing a `--no-pdf` switch to globally ignore the PDF format across all themes, resumes, and generators.

- Two different goals: **high-fidelity vs. high-quality**. Fidelity = a PDF rendering which is true to the spirit and intent of the user's resume and theme choice. Quality = a PDF that renders sharply and cleanly on a wide variety of devices. We want both but...

- Fidelity should usually trump quality in a resume context because users will forgive a little bit of fuzziness in the PDF output -- third-party browser previews and ugly "scanned PDFs" have helped pave the way here -- but what they won't forgive, is spending two days polishing their resume only to find that Markdown formatting isn't supported in their particular workflow.

- In terms of *fidelity*, both Phantom and wkhtmltopdf (and all other "point and click" HTML-driven resume generators) currently beat the LaTeX approach because the conversion from Markdown to HTML is trivial (relatively).

- To the extent we can implement Markdown-to-LaTeX, the LaTeX-driven approach starts to get better fidelity, and becomes a more attractive choice since it also produces better quality.

- If the user doesn't care about or use Markdown or HTML in his source resume, LaTeX also becomes a more attractive option.

- This functionality has to do double-duty in the desktop tool, where we can't count on users necessarily being tech-savvy or familiar with the ins and outs of package deployments.

**Comment by zhuangya** [comment]
sorry for lacking response lately

i'm busy learning how to drive recently.

however i will look into it in the near future :)

**Comment by hacksalot** [comment]
Congrats! No rush and stay safe.

I think we should consider dropping API-level support for wkhtmltopdf and Phantom in lieue of speaking to both tools, when present, via their CLI via `spawn` or similar. Dependency-wise, both packages are heavy and this is sort of an onerous requirement to put on users. I also don't trust `node-gyp` to work consistently across all platforms, and any native compilation poses issues for Travis as well. Not saying we can't work around them, but it doesn't seem worth the extra effort to integrate with these tools over an API which is only moderately more expressive than the CLI, if that makes sense.

**Comment by zhuangya** [comment]
> Not saying we can't work around them, but it doesn't seem worth the extra effort to integrate with these tools over an API which is only moderately more expressive than the CLI, if that makes sense.

make senses to me



> when present, via their CLI via spawn or similar

i think if the error handling is more robust as #83 or so, though that's kind of roll back to the start point of this project
